# Project Information
site_name: Gander OCA Knowledge Base
site_url: https://knowledgebase.ganderoceanic.ca
copyright: Copyright (C) Gander Oceanic OCA 2018-2025. All Rights Reserved. Not to be used for real world navigation. Flight simulation only.


plugins:
  - search
  - awesome-pages
  - git-revision-date-localized
  - mike

  
# Configuration
theme:
  name: material
  font:
    text: Mulish
  palette:
    scheme: czqo
  logo: https://ganderoceanic.ca/assets/resources/media/img/brand/sqr/ZQO_SQ_TSPWHITE.png
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking    
    - navigation.indexes
    - search.suggest
    - search.highlight
    - search.share
  favicon: https://ganderoceanic.ca/assets/resources/media/img/brand/sqr/ZQO_SQ_TSPWHITE.png

extra_css:
  - stylesheets/czqo.css

extra:
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/czqoocavatsim
    - icon: material/home
      link: https://ganderoceanic.ca
      name: Gander Oceanic main website 
  version:
    provider: mike


markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences

repo_url: https://github.com/czqoocavatsim/knowledgebase
repo_name: czqoocavatsim/knowledgebase
